### ISSUE TITLE
Error(Warning) while importing .sql

### ISSUE THREAD

**Issue by Hexer10** [boomix/BoomPanel#13]
Hi,

When I import to the mysql (mariadb) the database.sql I get this error:```#1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause ```

the tables are created anyway.

Btw nice work!

**Comment by nicedayzhu** [comment]
try mariadb 10.1.23
and enable InnoDB Storage Engine

**Comment by indietyp** [comment]
fixed with latest commit.
