### ISSUE TITLE
Doubts about the Project

### ISSUE THREAD

**Issue by crashzk** [boomix/BoomPanel#22]
First I would like to congratulate the project and its initiative.

As far as my doubts would be, would that Panel be an option to replace SourceBans?

Does he have market option inside it already? In case the players could log into the Panel and buy the privileges for the server, everything automatic in the case, it buys the privileges and is already activated on the server that it automatically chooses. It would be perfect if you had that option.

@boomix

**Comment by boomix** [comment]
The panel is in rework and the new version wont support any bans or mutes. Maybe in later versions that could be possible, but that seems pretty useless, as there is out sourcebans++, what has most of the features that you need for project and a lot of people actually use it. The goal of the project is to have easy admin control panel for the game servers (ban/kick/stats/console/player-search, etc), not whole webpage, where people can login and buy privileges.

**Comment by crashzk** [comment]
I understand, thanks for solving the doubts, who knows in the future it is possible to make these changes, for now thanks for the work already done.
